
trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Validation
    displayName: 'Compilacion proyecto iOS'
    jobs:
      - job: ValidationJob
        displayName: Validación iOS
        pool: server    
        timeoutInMinutes: 4320 # job times out in 3 days
        steps:   
        - task: ManualValidation@0
          timeoutInMinutes: 1440 # task times out in 1 day
          inputs:
              notifyUsers: |
                  marlo15.9909@outlook.com
                  marianazacariaschavez@hotmail.com
              instructions: 'Validar el trabajo y realizar el resumen del mismo'
              onTimeout: 'resume'
      - job: Job_CI_Blazor
        displayName: 'Compilacion Blazor'
        continueOnError: false
        dependsOn: ValidationJob
        steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'restore'
            projects: 'DataEncryption/DataEncryption.csproj'
            feedsToUse: 'select'
            vstsFeed: 'af2e86fe-2cee-437d-9bab-6fb66e7a5fd2'
        
        - task: DotNetCoreCLI@2
          inputs:
             command: 'build'
             projects: 'DataEncryption/DataEncryption.csproj'
             workingDirectory: '$(BuildConfiguration)'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'test'
            projects: '**/*[Tt]ests/*.csproj'
            workingDirectory: '$(BuildConfiguration)'
        - task: DotNetCoreCLI@2
          inputs:
            command: 'publish'
            publishWebProjects: true
            workingDirectory: '$(build.artifactstagingdirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'